### ISSUE TITLE
 user admin not found in db

### ISSUE THREAD

**Issue by Grayman-sama** [tumbl3w33d/nexus-oauth2-proxy-plugin#10]
**Expected**
OAuth2 authorization work

**Actual**
 admin com.github.tumbl3w33d.OAuth2ProxyRealm - call to doGetAuthorizationInfo found primary principle admin
 admin com.github.tumbl3w33d.h2.OAuth2ProxyUserStore - attempting to find user with id admin in db
 admin com.github.tumbl3w33d.h2.OAuth2ProxyUserDAO.read - ==>  Preparing: SELECT * FROM oauth2_proxy_user WHERE preferred_username = ?;
 admin com.github.tumbl3w33d.h2.OAuth2ProxyUserDAO.read - ==> Parameters: admin(String)
 admin com.github.tumbl3w33d.h2.OAuth2ProxyUserDAO.read - <==      Total: 0
 admin com.github.tumbl3w33d.h2.OAuth2ProxyUserStore - user admin not found in db
 admin com.github.tumbl3w33d.users.OAuth2ProxyUserManager - getUser unable to find a user object for admin
 admin com.github.tumbl3w33d.OAuth2ProxyRealm - unable to find user with principal admin in source OAuth2Proxy for authorization

**Relevant Versions**
Nexus version: 3.74 (on 3.71 same error)
Plugin version: 3.90.0

**Additional information**
oath2proxy work correct (all information present in console), but authorization not working

**Comment by tumbl3w33d** [comment]
Hi @Grayman-sama ,

please help me to understand your scenario: Are you trying to access Nexus programmatically (curl, gradle,…) or via UI, using the browser?

It looks like you are coming in with the browser, trying to access the Nexus UI as user `admin` which is the default administrative account in the local nexus user database. It is expected that this account cannot be found in the separate user database of the plugin.

One thing you might need to do is cleaning your browser state (cookies, local storage, etc., or just try with a private/incognito tab) from a previous nexus session using the `admin` when you were setting up the plugin.

Apart from that it is also possible that your proxy setup is insufficient yet. How does your setup look? Is it OAuth2Proxy and an additional one (like HAproxy or nginx) in front of Nexus and the OAuth2Proxy?

You can also try to have a look at the [troubleshooting](https://github.com/tumbl3w33d/nexus-oauth2-proxy-plugin?tab=readme-ov-file#troubleshooting) section which shows how to create a more verbose logger that might reveal information about headers that are received by Nexus.

**Comment by Grayman-sama** [comment]
Problem in our OAuth service, non standard output for scope, issue closed,

**Comment by tumbl3w33d** [comment]
Alright, glad you figured it out.
